---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ptrk.io
  resources:
  - scwexternalips
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ptrk.io
  resources:
  - scwexternalips/finalizers
  verbs:
  - update
- apiGroups:
  - ptrk.io
  resources:
  - scwexternalips/status
  verbs:
  - get
